// <auto-generated />
namespace Crytex.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixation_19_10_2015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixation_19_10_2015));
        
        string IMigrationMetadata.Id
        {
            get { return "201510182143126_Fixation_19_10_2015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
